### ISSUE TITLE
Layers non disponibili

### ISSUE THREAD

**Issue by ivn951** [SITA-RegionePiemonte/USC2020#2]
Vorrei segnalare la presenza di Layers non disponibili, durante la fase di apertura del progetto <**USC2020_v0.1-beta**>

![Layer_Nondisponibili](https://user-images.githubusercontent.com/9998772/126676841-17cea132-4a3a-4eb7-b74c-a0bc402fa6e0.JPG)

Si presume la necessità di una ri-mappatura delle sorgenti dati WMS : 
` http://gisserver.territorio.csi.it/geoserver/decsiraogc_********`

**Comment by silettog** [comment]
Stiamo verificando con i titolari dei dati il motivo della loro mancata disponibilità.

**Comment by silettog** [comment]
I dati alla base dei servizi non più raggiungibili sono in questo periodo oggetto di verifica. Fino a nuova data i servizi non sono pertanto più raggiungibili dal pubblico, ma ad accesso riservato alla PA. Per maggiori informazioni si prega di rivolgersi direttamente ai titolari dei singoli servizi, indicati sui metadati consultabili su www.geoportale.piemonte.it oppure inviando una mail a assistenza.sira@regione.piemonte.it

**Comment by ivn951** [comment]
Grazie.
